### ISSUE TITLE
Link backport PR to original issue

### ISSUE THREAD

**Issue by korthout** [zeebe-io/backport-action#3]
> Typically, when I backport a PR, I'll add a related to #123 (where 123 would be the original issue, not the PR being backported)

Original issue: https://github.com/zeebe-io/automation-lab/issues/43

**Comment by npepinpe** [comment]
I've opened a PR for zcl to pick up issues based on the `backport`, or `back port`, or `backports`, or `back ports`, keyword. So it would be amazing if we could also pick up the original issue number here for this, otherwise zcl will most likely pick up the PR for now. Which is OK, but not ideal :slightly_smiling_face:

**Comment by korthout** [comment]
#29 did not work out, but an easier solution might be found using regex looking for issue references in the description. See https://github.com/zeebe-io/backport-action/pull/29#issuecomment-847844175
