### ISSUE TITLE
Label original PR when backport PR is merged

### ISSUE THREAD

**Issue by negz** [zeebe-io/backport-action#73]
Currently when using this action my team has a habit of adding a `backported` label to the original PR (i.e. the PR labelled `backport some-branch` once the backport PR(s) are merged. This helps us get an idea of when we can cut a new release if we're waiting on several PRs to be backported.

I'm not sure how feasible it would be to actually build, but it would be really nice if this action was able to label PRs that had been successfully backported into all of the desired branches.

**Comment by korthout** [comment]
Hi @negz,

Thanks for sharing your idea. 

I agree that it would be useful, but I don't believe this should be part of this action's responsibilities:
- the backport action exists to automate backporting, not to do project management
- using the same trigger (pull request merged) but doing something completely different (only labelling a pull request, not creating a new backport pull request), seems to adds a lot of complexity unrelated to the original goal
- the backport action does not create all backport pull requests, so its not in control of all backport pull requests
  - it may fail and require manual action
  - someone might just create a backport manually because they're unaware its automated in your repo
- a pull request might be backported to multiple versions, how do you know that all have been merged?

I suggest to take a look at some of the actions that specialize in labelling pull requests on specific events. 

You could:
- create a workflow that is triggered when a pull request is merged
- filter out pull requests that don't use the word backport in their description or title (you can use string contains in the condition expression AFAIK)
- extract the original pull request ID from the description (this one might be a bit more difficult, but looks possible) - There might also be other ways to find this link
- and then use that labeller action to label that pull request
